### PR TITLE
feat: Add Barcode feature

### PR DESCRIPTION
**Pull request by xfqz86**

### CODE REVIEW

**Comment by MultiMote** [comment]
Hello again! Thank you for your contribution!
Can you add some settings to barcode caption font? Or increase font weight?

If we print with default settings (threshold 50%), text is unreadable.

image

If we increase threshold, text becomes readable, but barcode can be unreadable by scanners.

**Comment by xfqz86** [comment]
> Hello again! Thank you for your contribution! Can you add some settings to barcode caption font? Or increase font weight?
> 
> If we print with default settings (threshold 50%), text is unreadable.
> 
> image
> 
> If we increase threshold, text becomes readable, but barcode can be unreadable by scanners.

Fixed

**Comment by MultiMote** [comment]
It's better, but still needs some tweaks. There is a big problem with scaling barcode. At some scale levels barcode is blurry and after preprocessing it becomes unreadable by scanners.
Maybe there is some way to make barcode sharp (snap it to pixel grid or make some fixed zoom levels).

If you can't fix it, I'll merge pull request as-is.

**Comment by xfqz86** [comment]
> It's better, but still needs some tweaks. There is a big problem with scaling barcode. At some scale levels barcode is blurry and after preprocessing it becomes unreadable by scanners. Maybe there is some way to make barcode sharp (snap it to pixel grid or make some fixed zoom levels).
> 
> If you can't fix it, I'll merge pull request as-is.

To fulfill this requirement, the rendering function needs to be refactored, and there are a lot of calculations to be processed, which is very difficult.

**Pull request merged**
