### PR TITLE
feat: Zoom using the mouse wheel

### PR DESCRIPTION
**Pull request by xfqz86**

### CODE REVIEW

**Comment by MultiMote** [comment]
Nice feature!
But can you please invert zoom direction (usually scroll up means scale up in graphical editors)?

**Comment by MultiMote** [comment]
Also zoom reset will be useful too (with middle mouse button, for example).

**Comment by xfqz86** [comment]
> Also zoom reset will be useful too (with middle mouse button, for example).

Don't know why fabric canvas doesn't trigger mouse middle click event

**Comment by MultiMote** [comment]
```ts
this.on("mouse:down:before", (opt) => {
      const event = opt.e as MouseEvent;
      if(event.button == 1) {
        event.preventDefault();
        this.resetVirtualZoom();
      }
    });
```

**Comment by MultiMote** [comment]
Also found bug: if you select label template, zoom visually resets.

**Comment by xfqz86** [comment]
> Also found bug: if you select label template, zoom visually resets.

fixed

**Comment by xfqz86** [comment]
> ```ts
> this.on("mouse:down:before", (opt) => {
>       const event = opt.e as MouseEvent;
>       if(event.button == 1) {
>         event.preventDefault();
>         this.resetVirtualZoom();
>       }
>     });
> ```

commited

**Comment by dotnetdreamer** [comment]
Does this work with muti touch ?

**Comment by MultiMote** [comment]
@dotnetdreamer no, currently it for desktop users only.

**Pull request merged**
